# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List[Any],
    Dict[None, Any],
    Dict[bool, Any],
    Dict[float, Any],
    Dict[int, Any],
    Dict[str, Any],
]


    

StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive1'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive1 = TypedDict(
    'StringFilterRecursive1',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive2'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive2 = TypedDict(
    'StringFilterRecursive2',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive3'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive3 = TypedDict(
    'StringFilterRecursive3',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilterRecursive4'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)


StringFilterRecursive4 = TypedDict(
    'StringFilterRecursive4',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
                'mode': SortMode,
        'search': str,
    },
    total=False,
)


class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


    

DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive1'],
    },
    total=False,
)


DateTimeFilterRecursive1 = TypedDict(
    'DateTimeFilterRecursive1',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive2'],
    },
    total=False,
)


DateTimeFilterRecursive2 = TypedDict(
    'DateTimeFilterRecursive2',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive3'],
    },
    total=False,
)


DateTimeFilterRecursive3 = TypedDict(
    'DateTimeFilterRecursive3',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilterRecursive4'],
    },
    total=False,
)


DateTimeFilterRecursive4 = TypedDict(
    'DateTimeFilterRecursive4',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
            },
    total=False,
)


class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


    

BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive1'],
    },
    total=False,
)


BooleanFilterRecursive1 = TypedDict(
    'BooleanFilterRecursive1',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive2'],
    },
    total=False,
)


BooleanFilterRecursive2 = TypedDict(
    'BooleanFilterRecursive2',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive3'],
    },
    total=False,
)


BooleanFilterRecursive3 = TypedDict(
    'BooleanFilterRecursive3',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilterRecursive4'],
    },
    total=False,
)


BooleanFilterRecursive4 = TypedDict(
    'BooleanFilterRecursive4',
    {
        'equals': bool,
            },
    total=False,
)


class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


    

IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive1'],
    },
    total=False,
)


IntFilterRecursive1 = TypedDict(
    'IntFilterRecursive1',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive2'],
    },
    total=False,
)


IntFilterRecursive2 = TypedDict(
    'IntFilterRecursive2',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive3'],
    },
    total=False,
)


IntFilterRecursive3 = TypedDict(
    'IntFilterRecursive3',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilterRecursive4'],
    },
    total=False,
)


IntFilterRecursive4 = TypedDict(
    'IntFilterRecursive4',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
            },
    total=False,
)


class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
    

FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive1'],
    },
    total=False,
)


FloatFilterRecursive1 = TypedDict(
    'FloatFilterRecursive1',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive2'],
    },
    total=False,
)


FloatFilterRecursive2 = TypedDict(
    'FloatFilterRecursive2',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive3'],
    },
    total=False,
)


FloatFilterRecursive3 = TypedDict(
    'FloatFilterRecursive3',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilterRecursive4'],
    },
    total=False,
)


FloatFilterRecursive4 = TypedDict(
    'FloatFilterRecursive4',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
            },
    total=False,
)


class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


    

BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive1'],
    },
    total=False,
)


BytesFilterRecursive1 = TypedDict(
    'BytesFilterRecursive1',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive2'],
    },
    total=False,
)


BytesFilterRecursive2 = TypedDict(
    'BytesFilterRecursive2',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive3'],
    },
    total=False,
)


BytesFilterRecursive3 = TypedDict(
    'BytesFilterRecursive3',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilterRecursive4'],
    },
    total=False,
)


BytesFilterRecursive4 = TypedDict(
    'BytesFilterRecursive4',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
            },
    total=False,
)


class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


    

DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive1'],
    },
    total=False,
)


DecimalFilterRecursive1 = TypedDict(
    'DecimalFilterRecursive1',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive2'],
    },
    total=False,
)


DecimalFilterRecursive2 = TypedDict(
    'DecimalFilterRecursive2',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive3'],
    },
    total=False,
)


DecimalFilterRecursive3 = TypedDict(
    'DecimalFilterRecursive3',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilterRecursive4'],
    },
    total=False,
)


DecimalFilterRecursive4 = TypedDict(
    'DecimalFilterRecursive4',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
            },
    total=False,
)


class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# User types

class UserOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the User create method"""
    id: _str
    isSubscribed: _bool
    subscription: Optional['fields.Json']
    freePlanUsage: Optional['fields.Json']
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: Optional['fields.Json']
    agentSessions: 'ChatSessionCreateManyNestedWithoutRelationsInput'


class UserCreateInput(UserOptionalCreateInput):
    """Required arguments to the User create method"""
    email: _str
    password: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class UserOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the User create method, without relations"""
    id: _str
    isSubscribed: _bool
    subscription: Optional['fields.Json']
    freePlanUsage: Optional['fields.Json']
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: Optional['fields.Json']


class UserCreateWithoutRelationsInput(UserOptionalCreateWithoutRelationsInput):
    """Required arguments to the User create method, without relations"""
    email: _str
    password: _str

class UserConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'UserCreateWithoutRelationsInput'
    where: 'UserWhereUniqueInput'

class UserCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'


class UserCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['UserCreateWithoutRelationsInput', List['UserCreateWithoutRelationsInput']]
    connect: Union['UserWhereUniqueInput', List['UserWhereUniqueInput']]
    connect_or_create: Union['UserConnectOrCreateWithoutRelationsInput', List['UserConnectOrCreateWithoutRelationsInput']]

_UserWhereUnique_id_Input = TypedDict(
    '_UserWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

_UserWhereUnique_email_Input = TypedDict(
    '_UserWhereUnique_email_Input',
    {
        'email': '_str',
    },
    total=True
)

UserWhereUniqueInput = Union[
    '_UserWhereUnique_id_Input',
    '_UserWhereUnique_email_Input',
]


class UserUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    email: _str
    password: _str
    isSubscribed: _bool
    subscription: Optional['fields.Json']
    freePlanUsage: Optional['fields.Json']
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: Optional['fields.Json']
    agentSessions: 'ChatSessionUpdateManyWithoutRelationsInput'


class UserUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    email: _str
    password: _str
    isSubscribed: _bool
    subscription: Optional['fields.Json']
    freePlanUsage: Optional['fields.Json']
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: Optional['fields.Json']


class UserUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['UserCreateWithoutRelationsInput']
    connect: List['UserWhereUniqueInput']
    connect_or_create: List['UserConnectOrCreateWithoutRelationsInput']
    set: List['UserWhereUniqueInput']
    disconnect: List['UserWhereUniqueInput']
    delete: List['UserWhereUniqueInput']

    # TODO
    # update: List['UserUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['UserUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['UserScalarWhereInput']
    # upsert: List['UserUpserteWithWhereUniqueWithoutRelationsInput']


class UserUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'UserCreateWithoutRelationsInput'
    connect: 'UserWhereUniqueInput'
    connect_or_create: 'UserConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'UserUpdateInput'
    # upsert: 'UserUpsertWithoutRelationsInput'


class UserUpsertInput(TypedDict):
    create: 'UserCreateInput'
    update: 'UserUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_User_id_OrderByInput = TypedDict(
    '_User_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_User_email_OrderByInput = TypedDict(
    '_User_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_User_password_OrderByInput = TypedDict(
    '_User_password_OrderByInput',
    {
        'password': 'SortOrder',
    },
    total=True
)

_User_isSubscribed_OrderByInput = TypedDict(
    '_User_isSubscribed_OrderByInput',
    {
        'isSubscribed': 'SortOrder',
    },
    total=True
)

_User_subscription_OrderByInput = TypedDict(
    '_User_subscription_OrderByInput',
    {
        'subscription': 'SortOrder',
    },
    total=True
)

_User_freePlanUsage_OrderByInput = TypedDict(
    '_User_freePlanUsage_OrderByInput',
    {
        'freePlanUsage': 'SortOrder',
    },
    total=True
)

_User_role_OrderByInput = TypedDict(
    '_User_role_OrderByInput',
    {
        'role': 'SortOrder',
    },
    total=True
)

_User_createdAt_OrderByInput = TypedDict(
    '_User_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_User_updatedAt_OrderByInput = TypedDict(
    '_User_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

_User_paymentStatus_OrderByInput = TypedDict(
    '_User_paymentStatus_OrderByInput',
    {
        'paymentStatus': 'SortOrder',
    },
    total=True
)

_User_plan_OrderByInput = TypedDict(
    '_User_plan_OrderByInput',
    {
        'plan': 'SortOrder',
    },
    total=True
)

_User_notifications_OrderByInput = TypedDict(
    '_User_notifications_OrderByInput',
    {
        'notifications': 'SortOrder',
    },
    total=True
)

_User_RelevanceInner = TypedDict(
    '_User_RelevanceInner',
    {
        'fields': 'List[UserScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_User_RelevanceOrderByInput = TypedDict(
    '_User_RelevanceOrderByInput',
    {
        '_relevance': '_User_RelevanceInner',
    },
    total=True
)

UserOrderByInput = Union[
    '_User_id_OrderByInput',
    '_User_email_OrderByInput',
    '_User_password_OrderByInput',
    '_User_isSubscribed_OrderByInput',
    '_User_subscription_OrderByInput',
    '_User_freePlanUsage_OrderByInput',
    '_User_role_OrderByInput',
    '_User_createdAt_OrderByInput',
    '_User_updatedAt_OrderByInput',
    '_User_paymentStatus_OrderByInput',
    '_User_plan_OrderByInput',
    '_User_notifications_OrderByInput',
    '_User_RelevanceOrderByInput',
]



# recursive User types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

UserRelationFilter = TypedDict(
    'UserRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class UserListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class UserInclude(TypedDict, total=False):
    """User relational arguments"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromUser']


    

class UserIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromUserRecursive1']


class UserIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromUserRecursive2']


class UserIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromUserRecursive3']


class UserIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromUserRecursive4']


class UserIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class UserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyUserArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class ChatSessionIncludeFromUser(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive1']


class ChatSessionIncludeFromUserRecursive1(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive2']


class ChatSessionIncludeFromUserRecursive2(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive3']


class ChatSessionIncludeFromUserRecursive3(TypedDict, total=False):
    """Relational arguments for User"""
    user: Union[bool, 'UserArgsFromUserRecursive4']


class ChatSessionIncludeFromUserRecursive4(TypedDict, total=False):
    """Relational arguments for User"""

    

class ChatSessionArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    include: 'ChatSessionIncludeFromChatSessionRecursive1'


class ChatSessionArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    include: 'ChatSessionIncludeFromChatSessionRecursive2'


class ChatSessionArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    include: 'ChatSessionIncludeFromChatSessionRecursive3'


class ChatSessionArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    include: 'ChatSessionIncludeFromChatSessionRecursive4'


class ChatSessionArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    
    

class FindManyChatSessionArgsFromUser(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive1'


class FindManyChatSessionArgsFromUserRecursive1(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive2'


class FindManyChatSessionArgsFromUserRecursive2(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive3'


class FindManyChatSessionArgsFromUserRecursive3(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive4'


class FindManyChatSessionArgsFromUserRecursive4(TypedDict, total=False):
    """Arguments for User"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    


FindManyUserArgs = FindManyUserArgsFromUser
FindFirstUserArgs = FindManyUserArgsFromUser


    

class UserWhereInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    isSubscribed: Union[_bool, 'types.BooleanFilter']
    subscription: Union[None, 'fields.Json', 'types.JsonFilter']
    freePlanUsage: Union[None, 'fields.Json', 'types.JsonFilter']
    role: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    paymentStatus: Union[_str, 'types.StringFilter']
    plan: Union[_str, 'types.StringFilter']
    notifications: Union[None, 'fields.Json', 'types.JsonFilter']
    agentSessions: 'ChatSessionListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive1', List['UserWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive1']
    OR: List['UserWhereInputRecursive1']
    NOT: List['UserWhereInputRecursive1']


class UserWhereInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    isSubscribed: Union[_bool, 'types.BooleanFilter']
    subscription: Union[None, 'fields.Json', 'types.JsonFilter']
    freePlanUsage: Union[None, 'fields.Json', 'types.JsonFilter']
    role: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    paymentStatus: Union[_str, 'types.StringFilter']
    plan: Union[_str, 'types.StringFilter']
    notifications: Union[None, 'fields.Json', 'types.JsonFilter']
    agentSessions: 'ChatSessionListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive2', List['UserWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive2']
    OR: List['UserWhereInputRecursive2']
    NOT: List['UserWhereInputRecursive2']


class UserWhereInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    isSubscribed: Union[_bool, 'types.BooleanFilter']
    subscription: Union[None, 'fields.Json', 'types.JsonFilter']
    freePlanUsage: Union[None, 'fields.Json', 'types.JsonFilter']
    role: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    paymentStatus: Union[_str, 'types.StringFilter']
    plan: Union[_str, 'types.StringFilter']
    notifications: Union[None, 'fields.Json', 'types.JsonFilter']
    agentSessions: 'ChatSessionListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive3', List['UserWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive3']
    OR: List['UserWhereInputRecursive3']
    NOT: List['UserWhereInputRecursive3']


class UserWhereInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    isSubscribed: Union[_bool, 'types.BooleanFilter']
    subscription: Union[None, 'fields.Json', 'types.JsonFilter']
    freePlanUsage: Union[None, 'fields.Json', 'types.JsonFilter']
    role: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    paymentStatus: Union[_str, 'types.StringFilter']
    plan: Union[_str, 'types.StringFilter']
    notifications: Union[None, 'fields.Json', 'types.JsonFilter']
    agentSessions: 'ChatSessionListRelationFilter'

    # should be noted that AND and NOT should be Union['UserWhereInputRecursive4', List['UserWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['UserWhereInputRecursive4']
    OR: List['UserWhereInputRecursive4']
    NOT: List['UserWhereInputRecursive4']


class UserWhereInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    password: Union[_str, 'types.StringFilter']
    isSubscribed: Union[_bool, 'types.BooleanFilter']
    subscription: Union[None, 'fields.Json', 'types.JsonFilter']
    freePlanUsage: Union[None, 'fields.Json', 'types.JsonFilter']
    role: Union[_str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']
    paymentStatus: Union[_str, 'types.StringFilter']
    plan: Union[_str, 'types.StringFilter']
    notifications: Union[None, 'fields.Json', 'types.JsonFilter']
    agentSessions: 'ChatSessionListRelationFilter'



# aggregate User types


    

class UserScalarWhereWithAggregatesInput(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    isSubscribed: Union[_bool, 'types.BooleanWithAggregatesFilter']
    subscription: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    freePlanUsage: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    role: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    paymentStatus: Union[_str, 'types.StringWithAggregatesFilter']
    plan: Union[_str, 'types.StringWithAggregatesFilter']
    notifications: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive1']
    OR: List['UserScalarWhereWithAggregatesInputRecursive1']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive1']


class UserScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    isSubscribed: Union[_bool, 'types.BooleanWithAggregatesFilter']
    subscription: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    freePlanUsage: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    role: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    paymentStatus: Union[_str, 'types.StringWithAggregatesFilter']
    plan: Union[_str, 'types.StringWithAggregatesFilter']
    notifications: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive2']
    OR: List['UserScalarWhereWithAggregatesInputRecursive2']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive2']


class UserScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    isSubscribed: Union[_bool, 'types.BooleanWithAggregatesFilter']
    subscription: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    freePlanUsage: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    role: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    paymentStatus: Union[_str, 'types.StringWithAggregatesFilter']
    plan: Union[_str, 'types.StringWithAggregatesFilter']
    notifications: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive3']
    OR: List['UserScalarWhereWithAggregatesInputRecursive3']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive3']


class UserScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    isSubscribed: Union[_bool, 'types.BooleanWithAggregatesFilter']
    subscription: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    freePlanUsage: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    role: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    paymentStatus: Union[_str, 'types.StringWithAggregatesFilter']
    plan: Union[_str, 'types.StringWithAggregatesFilter']
    notifications: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['UserScalarWhereWithAggregatesInputRecursive4']
    OR: List['UserScalarWhereWithAggregatesInputRecursive4']
    NOT: List['UserScalarWhereWithAggregatesInputRecursive4']


class UserScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """User arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    password: Union[_str, 'types.StringWithAggregatesFilter']
    isSubscribed: Union[_bool, 'types.BooleanWithAggregatesFilter']
    subscription: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    freePlanUsage: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    role: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    paymentStatus: Union[_str, 'types.StringWithAggregatesFilter']
    plan: Union[_str, 'types.StringWithAggregatesFilter']
    notifications: Union['fields.Json', 'types.JsonWithAggregatesFilter']



class UserGroupByOutput(TypedDict, total=False):
    id: _str
    email: _str
    password: _str
    isSubscribed: _bool
    subscription: 'fields.Json'
    freePlanUsage: 'fields.Json'
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: 'fields.Json'
    _sum: 'UserSumAggregateOutput'
    _avg: 'UserAvgAggregateOutput'
    _min: 'UserMinAggregateOutput'
    _max: 'UserMaxAggregateOutput'
    _count: 'UserCountAggregateOutput'


class UserAvgAggregateOutput(TypedDict, total=False):
    """User output for aggregating averages"""


class UserSumAggregateOutput(TypedDict, total=False):
    """User output for aggregating sums"""


class UserScalarAggregateOutput(TypedDict, total=False):
    """User output including scalar fields"""
    id: _str
    email: _str
    password: _str
    isSubscribed: _bool
    subscription: 'fields.Json'
    freePlanUsage: 'fields.Json'
    role: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    paymentStatus: _str
    plan: _str
    notifications: 'fields.Json'


UserMinAggregateOutput = UserScalarAggregateOutput
UserMaxAggregateOutput = UserScalarAggregateOutput


class UserMaxAggregateInput(TypedDict, total=False):
    """User input for aggregating by max"""
    id: bool
    email: bool
    password: bool
    isSubscribed: bool
    subscription: bool
    freePlanUsage: bool
    role: bool
    createdAt: bool
    updatedAt: bool
    paymentStatus: bool
    plan: bool
    notifications: bool


class UserMinAggregateInput(TypedDict, total=False):
    """User input for aggregating by min"""
    id: bool
    email: bool
    password: bool
    isSubscribed: bool
    subscription: bool
    freePlanUsage: bool
    role: bool
    createdAt: bool
    updatedAt: bool
    paymentStatus: bool
    plan: bool
    notifications: bool


class UserNumberAggregateInput(TypedDict, total=False):
    """User input for aggregating numbers"""


UserAvgAggregateInput = UserNumberAggregateInput
UserSumAggregateInput = UserNumberAggregateInput


UserCountAggregateInput = TypedDict(
    'UserCountAggregateInput',
    {
        'id': bool,
        'email': bool,
        'password': bool,
        'isSubscribed': bool,
        'subscription': bool,
        'freePlanUsage': bool,
        'role': bool,
        'createdAt': bool,
        'updatedAt': bool,
        'paymentStatus': bool,
        'plan': bool,
        'notifications': bool,
        '_all': bool,
    },
    total=False,
)

UserCountAggregateOutput = TypedDict(
    'UserCountAggregateOutput',
    {
        'id': int,
        'email': int,
        'password': int,
        'isSubscribed': int,
        'subscription': int,
        'freePlanUsage': int,
        'role': int,
        'createdAt': int,
        'updatedAt': int,
        'paymentStatus': int,
        'plan': int,
        'notifications': int,
        '_all': int,
    },
    total=False,
)


UserKeys = Literal[
    'id',
    'email',
    'password',
    'isSubscribed',
    'subscription',
    'freePlanUsage',
    'role',
    'createdAt',
    'updatedAt',
    'paymentStatus',
    'plan',
    'notifications',
    'agentSessions',
]
UserScalarFieldKeys = Literal[
    'id',
    'email',
    'password',
    'isSubscribed',
    'subscription',
    'freePlanUsage',
    'role',
    'createdAt',
    'updatedAt',
    'paymentStatus',
    'plan',
    'notifications',
]
UserScalarFieldKeysT = TypeVar('UserScalarFieldKeysT', bound=UserScalarFieldKeys)

UserRelationalFieldKeys = Literal[
        'agentSessions',
    ]

# ChatSession types

class ChatSessionOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the ChatSession create method"""
    id: _str
    user_id: _str
    user: 'UserCreateNestedWithoutRelationsInput'
    created_at: datetime.datetime


class ChatSessionCreateInput(ChatSessionOptionalCreateInput):
    """Required arguments to the ChatSession create method"""
    session_id: _str
    history: 'fields.Json'


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class ChatSessionOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the ChatSession create method, without relations"""
    id: _str
    user_id: _str
    created_at: datetime.datetime


class ChatSessionCreateWithoutRelationsInput(ChatSessionOptionalCreateWithoutRelationsInput):
    """Required arguments to the ChatSession create method, without relations"""
    session_id: _str
    history: 'fields.Json'

class ChatSessionConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'ChatSessionCreateWithoutRelationsInput'
    where: 'ChatSessionWhereUniqueInput'

class ChatSessionCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'ChatSessionCreateWithoutRelationsInput'
    connect: 'ChatSessionWhereUniqueInput'
    connect_or_create: 'ChatSessionConnectOrCreateWithoutRelationsInput'


class ChatSessionCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['ChatSessionCreateWithoutRelationsInput', List['ChatSessionCreateWithoutRelationsInput']]
    connect: Union['ChatSessionWhereUniqueInput', List['ChatSessionWhereUniqueInput']]
    connect_or_create: Union['ChatSessionConnectOrCreateWithoutRelationsInput', List['ChatSessionConnectOrCreateWithoutRelationsInput']]

_ChatSessionWhereUnique_id_Input = TypedDict(
    '_ChatSessionWhereUnique_id_Input',
    {
        'id': '_str',
    },
    total=True
)

_ChatSessionWhereUnique_session_id_Input = TypedDict(
    '_ChatSessionWhereUnique_session_id_Input',
    {
        'session_id': '_str',
    },
    total=True
)

ChatSessionWhereUniqueInput = Union[
    '_ChatSessionWhereUnique_id_Input',
    '_ChatSessionWhereUnique_session_id_Input',
]


class ChatSessionUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: _str
    session_id: _str
    user: 'UserUpdateOneWithoutRelationsInput'
    created_at: datetime.datetime
    history: 'fields.Json'


class ChatSessionUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: _str
    session_id: _str
    created_at: datetime.datetime
    history: 'fields.Json'


class ChatSessionUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['ChatSessionCreateWithoutRelationsInput']
    connect: List['ChatSessionWhereUniqueInput']
    connect_or_create: List['ChatSessionConnectOrCreateWithoutRelationsInput']
    set: List['ChatSessionWhereUniqueInput']
    disconnect: List['ChatSessionWhereUniqueInput']
    delete: List['ChatSessionWhereUniqueInput']

    # TODO
    # update: List['ChatSessionUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['ChatSessionUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['ChatSessionScalarWhereInput']
    # upsert: List['ChatSessionUpserteWithWhereUniqueWithoutRelationsInput']


class ChatSessionUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'ChatSessionCreateWithoutRelationsInput'
    connect: 'ChatSessionWhereUniqueInput'
    connect_or_create: 'ChatSessionConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'ChatSessionUpdateInput'
    # upsert: 'ChatSessionUpsertWithoutRelationsInput'


class ChatSessionUpsertInput(TypedDict):
    create: 'ChatSessionCreateInput'
    update: 'ChatSessionUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_ChatSession_id_OrderByInput = TypedDict(
    '_ChatSession_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_ChatSession_session_id_OrderByInput = TypedDict(
    '_ChatSession_session_id_OrderByInput',
    {
        'session_id': 'SortOrder',
    },
    total=True
)

_ChatSession_user_id_OrderByInput = TypedDict(
    '_ChatSession_user_id_OrderByInput',
    {
        'user_id': 'SortOrder',
    },
    total=True
)

_ChatSession_created_at_OrderByInput = TypedDict(
    '_ChatSession_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_ChatSession_history_OrderByInput = TypedDict(
    '_ChatSession_history_OrderByInput',
    {
        'history': 'SortOrder',
    },
    total=True
)

_ChatSession_RelevanceInner = TypedDict(
    '_ChatSession_RelevanceInner',
    {
        'fields': 'List[ChatSessionScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_ChatSession_RelevanceOrderByInput = TypedDict(
    '_ChatSession_RelevanceOrderByInput',
    {
        '_relevance': '_ChatSession_RelevanceInner',
    },
    total=True
)

ChatSessionOrderByInput = Union[
    '_ChatSession_id_OrderByInput',
    '_ChatSession_session_id_OrderByInput',
    '_ChatSession_user_id_OrderByInput',
    '_ChatSession_created_at_OrderByInput',
    '_ChatSession_history_OrderByInput',
    '_ChatSession_RelevanceOrderByInput',
]



# recursive ChatSession types
# TODO: cleanup these types


# Dict[str, Any] is a mypy limitation
# see https://github.com/RobertCraigie/prisma-client-py/issues/45
# switch to pyright for improved types, see https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/

ChatSessionRelationFilter = TypedDict(
    'ChatSessionRelationFilter',
    {
        'is': 'Dict[str, Any]',
        'is_not': 'Dict[str, Any]',
    },
    total=False,
)


class ChatSessionListRelationFilter(TypedDict, total=False):
    some: 'Dict[str, Any]'
    none: 'Dict[str, Any]'
    every: 'Dict[str, Any]'


class ChatSessionInclude(TypedDict, total=False):
    """ChatSession relational arguments"""
    user: Union[bool, 'UserArgsFromChatSession']


    

class UserIncludeFromChatSession(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromChatSessionRecursive1']


class UserIncludeFromChatSessionRecursive1(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromChatSessionRecursive2']


class UserIncludeFromChatSessionRecursive2(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromChatSessionRecursive3']


class UserIncludeFromChatSessionRecursive3(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    agentSessions: Union[bool, 'FindManyChatSessionArgsFromChatSessionRecursive4']


class UserIncludeFromChatSessionRecursive4(TypedDict, total=False):
    """Relational arguments for ChatSession"""

    

class UserArgsFromChatSession(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'UserIncludeFromUserRecursive1'


class UserArgsFromChatSessionRecursive1(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'UserIncludeFromUserRecursive2'


class UserArgsFromChatSessionRecursive2(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'UserIncludeFromUserRecursive3'


class UserArgsFromChatSessionRecursive3(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'UserIncludeFromUserRecursive4'


class UserArgsFromChatSessionRecursive4(TypedDict, total=False):
    """Arguments for ChatSession"""
    
    

class FindManyUserArgsFromChatSession(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive1'


class FindManyUserArgsFromChatSessionRecursive1(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive2'


class FindManyUserArgsFromChatSessionRecursive2(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive3'


class FindManyUserArgsFromChatSessionRecursive3(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    include: 'UserIncludeFromUserRecursive4'


class FindManyUserArgsFromChatSessionRecursive4(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['UserOrderByInput', List['UserOrderByInput']]
    where: 'UserWhereInput'
    cursor: 'UserWhereUniqueInput'
    distinct: List['UserScalarFieldKeys']
    
    

class ChatSessionIncludeFromChatSession(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    user: Union[bool, 'UserArgsFromChatSessionRecursive1']


class ChatSessionIncludeFromChatSessionRecursive1(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    user: Union[bool, 'UserArgsFromChatSessionRecursive2']


class ChatSessionIncludeFromChatSessionRecursive2(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    user: Union[bool, 'UserArgsFromChatSessionRecursive3']


class ChatSessionIncludeFromChatSessionRecursive3(TypedDict, total=False):
    """Relational arguments for ChatSession"""
    user: Union[bool, 'UserArgsFromChatSessionRecursive4']


class ChatSessionIncludeFromChatSessionRecursive4(TypedDict, total=False):
    """Relational arguments for ChatSession"""

    

class ChatSessionArgsFromChatSession(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'ChatSessionIncludeFromChatSessionRecursive1'


class ChatSessionArgsFromChatSessionRecursive1(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'ChatSessionIncludeFromChatSessionRecursive2'


class ChatSessionArgsFromChatSessionRecursive2(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'ChatSessionIncludeFromChatSessionRecursive3'


class ChatSessionArgsFromChatSessionRecursive3(TypedDict, total=False):
    """Arguments for ChatSession"""
    include: 'ChatSessionIncludeFromChatSessionRecursive4'


class ChatSessionArgsFromChatSessionRecursive4(TypedDict, total=False):
    """Arguments for ChatSession"""
    
    

class FindManyChatSessionArgsFromChatSession(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive1'


class FindManyChatSessionArgsFromChatSessionRecursive1(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive2'


class FindManyChatSessionArgsFromChatSessionRecursive2(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive3'


class FindManyChatSessionArgsFromChatSessionRecursive3(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    include: 'ChatSessionIncludeFromChatSessionRecursive4'


class FindManyChatSessionArgsFromChatSessionRecursive4(TypedDict, total=False):
    """Arguments for ChatSession"""
    take: int
    skip: int
    order_by: Union['ChatSessionOrderByInput', List['ChatSessionOrderByInput']]
    where: 'ChatSessionWhereInput'
    cursor: 'ChatSessionWhereUniqueInput'
    distinct: List['ChatSessionScalarFieldKeys']
    


FindManyChatSessionArgs = FindManyChatSessionArgsFromChatSession
FindFirstChatSessionArgs = FindManyChatSessionArgsFromChatSession


    

class ChatSessionWhereInput(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    session_id: Union[_str, 'types.StringFilter']
    user_id: Union[_str, 'types.StringFilter']
    user: 'UserRelationFilter'
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    history: Union['fields.Json', 'types.JsonFilter']

    # should be noted that AND and NOT should be Union['ChatSessionWhereInputRecursive1', List['ChatSessionWhereInputRecursive1']]
    # but this causes mypy to hang :/
    AND: List['ChatSessionWhereInputRecursive1']
    OR: List['ChatSessionWhereInputRecursive1']
    NOT: List['ChatSessionWhereInputRecursive1']


class ChatSessionWhereInputRecursive1(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    session_id: Union[_str, 'types.StringFilter']
    user_id: Union[_str, 'types.StringFilter']
    user: 'UserRelationFilter'
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    history: Union['fields.Json', 'types.JsonFilter']

    # should be noted that AND and NOT should be Union['ChatSessionWhereInputRecursive2', List['ChatSessionWhereInputRecursive2']]
    # but this causes mypy to hang :/
    AND: List['ChatSessionWhereInputRecursive2']
    OR: List['ChatSessionWhereInputRecursive2']
    NOT: List['ChatSessionWhereInputRecursive2']


class ChatSessionWhereInputRecursive2(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    session_id: Union[_str, 'types.StringFilter']
    user_id: Union[_str, 'types.StringFilter']
    user: 'UserRelationFilter'
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    history: Union['fields.Json', 'types.JsonFilter']

    # should be noted that AND and NOT should be Union['ChatSessionWhereInputRecursive3', List['ChatSessionWhereInputRecursive3']]
    # but this causes mypy to hang :/
    AND: List['ChatSessionWhereInputRecursive3']
    OR: List['ChatSessionWhereInputRecursive3']
    NOT: List['ChatSessionWhereInputRecursive3']


class ChatSessionWhereInputRecursive3(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    session_id: Union[_str, 'types.StringFilter']
    user_id: Union[_str, 'types.StringFilter']
    user: 'UserRelationFilter'
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    history: Union['fields.Json', 'types.JsonFilter']

    # should be noted that AND and NOT should be Union['ChatSessionWhereInputRecursive4', List['ChatSessionWhereInputRecursive4']]
    # but this causes mypy to hang :/
    AND: List['ChatSessionWhereInputRecursive4']
    OR: List['ChatSessionWhereInputRecursive4']
    NOT: List['ChatSessionWhereInputRecursive4']


class ChatSessionWhereInputRecursive4(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringFilter']
    session_id: Union[_str, 'types.StringFilter']
    user_id: Union[_str, 'types.StringFilter']
    user: 'UserRelationFilter'
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']
    history: Union['fields.Json', 'types.JsonFilter']



# aggregate ChatSession types


    

class ChatSessionScalarWhereWithAggregatesInput(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    session_id: Union[_str, 'types.StringWithAggregatesFilter']
    user_id: Union[_str, 'types.StringWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    history: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['ChatSessionScalarWhereWithAggregatesInputRecursive1']
    OR: List['ChatSessionScalarWhereWithAggregatesInputRecursive1']
    NOT: List['ChatSessionScalarWhereWithAggregatesInputRecursive1']


class ChatSessionScalarWhereWithAggregatesInputRecursive1(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    session_id: Union[_str, 'types.StringWithAggregatesFilter']
    user_id: Union[_str, 'types.StringWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    history: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['ChatSessionScalarWhereWithAggregatesInputRecursive2']
    OR: List['ChatSessionScalarWhereWithAggregatesInputRecursive2']
    NOT: List['ChatSessionScalarWhereWithAggregatesInputRecursive2']


class ChatSessionScalarWhereWithAggregatesInputRecursive2(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    session_id: Union[_str, 'types.StringWithAggregatesFilter']
    user_id: Union[_str, 'types.StringWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    history: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['ChatSessionScalarWhereWithAggregatesInputRecursive3']
    OR: List['ChatSessionScalarWhereWithAggregatesInputRecursive3']
    NOT: List['ChatSessionScalarWhereWithAggregatesInputRecursive3']


class ChatSessionScalarWhereWithAggregatesInputRecursive3(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    session_id: Union[_str, 'types.StringWithAggregatesFilter']
    user_id: Union[_str, 'types.StringWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    history: Union['fields.Json', 'types.JsonWithAggregatesFilter']

    AND: List['ChatSessionScalarWhereWithAggregatesInputRecursive4']
    OR: List['ChatSessionScalarWhereWithAggregatesInputRecursive4']
    NOT: List['ChatSessionScalarWhereWithAggregatesInputRecursive4']


class ChatSessionScalarWhereWithAggregatesInputRecursive4(TypedDict, total=False):
    """ChatSession arguments for searching"""
    id: Union[_str, 'types.StringWithAggregatesFilter']
    session_id: Union[_str, 'types.StringWithAggregatesFilter']
    user_id: Union[_str, 'types.StringWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    history: Union['fields.Json', 'types.JsonWithAggregatesFilter']



class ChatSessionGroupByOutput(TypedDict, total=False):
    id: _str
    session_id: _str
    user_id: _str
    created_at: datetime.datetime
    history: 'fields.Json'
    _sum: 'ChatSessionSumAggregateOutput'
    _avg: 'ChatSessionAvgAggregateOutput'
    _min: 'ChatSessionMinAggregateOutput'
    _max: 'ChatSessionMaxAggregateOutput'
    _count: 'ChatSessionCountAggregateOutput'


class ChatSessionAvgAggregateOutput(TypedDict, total=False):
    """ChatSession output for aggregating averages"""


class ChatSessionSumAggregateOutput(TypedDict, total=False):
    """ChatSession output for aggregating sums"""


class ChatSessionScalarAggregateOutput(TypedDict, total=False):
    """ChatSession output including scalar fields"""
    id: _str
    session_id: _str
    user_id: _str
    created_at: datetime.datetime
    history: 'fields.Json'


ChatSessionMinAggregateOutput = ChatSessionScalarAggregateOutput
ChatSessionMaxAggregateOutput = ChatSessionScalarAggregateOutput


class ChatSessionMaxAggregateInput(TypedDict, total=False):
    """ChatSession input for aggregating by max"""
    id: bool
    session_id: bool
    user_id: bool
    created_at: bool
    history: bool


class ChatSessionMinAggregateInput(TypedDict, total=False):
    """ChatSession input for aggregating by min"""
    id: bool
    session_id: bool
    user_id: bool
    created_at: bool
    history: bool


class ChatSessionNumberAggregateInput(TypedDict, total=False):
    """ChatSession input for aggregating numbers"""


ChatSessionAvgAggregateInput = ChatSessionNumberAggregateInput
ChatSessionSumAggregateInput = ChatSessionNumberAggregateInput


ChatSessionCountAggregateInput = TypedDict(
    'ChatSessionCountAggregateInput',
    {
        'id': bool,
        'session_id': bool,
        'user_id': bool,
        'created_at': bool,
        'history': bool,
        '_all': bool,
    },
    total=False,
)

ChatSessionCountAggregateOutput = TypedDict(
    'ChatSessionCountAggregateOutput',
    {
        'id': int,
        'session_id': int,
        'user_id': int,
        'created_at': int,
        'history': int,
        '_all': int,
    },
    total=False,
)


ChatSessionKeys = Literal[
    'id',
    'session_id',
    'user_id',
    'user',
    'created_at',
    'history',
]
ChatSessionScalarFieldKeys = Literal[
    'id',
    'session_id',
    'user_id',
    'created_at',
    'history',
]
ChatSessionScalarFieldKeysT = TypeVar('ChatSessionScalarFieldKeysT', bound=ChatSessionScalarFieldKeys)

ChatSessionRelationalFieldKeys = Literal[
        'user',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields